### ISSUE TITLE
aspectFill image support

### ISSUE THREAD

**Issue by jofax** [ipagong/PGPhotoViewer-Swift#2]
Hi

Is there a way to support images in an aspect fill?  I mean if image is portrait, can be fill on the screen?

**Comment by ipagong** [comment]
You can try customizing imageView in ZoomScrollView. 
It has contentView that implements ZoomContentViewProtocol.
and you can make a new content view with ZoomContentViewProtocol and then inject the content view class to zoomingscrollview when called initializing method.
